name: Android CI

on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  gradle:
    name: Gradle CI Build
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/*.gradle.kts') }}

    - name: Build project
      run: |
        ./gradlew :app:assemblerelease
    - name: Sign Android release
      if: success()
      id: sign
      uses: r0adkll/sign-android-release@v1.0.4
      env:
        BUILD_TOOLS_VERSION: "31.0.0"
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Upload built apk
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: snapshot
        path: |
            ${{ github.workspace }}/app/build/outputs/apk
    - name: Post to channel
      if: contains(github.event.head_commit.message, '[skip post]') == false
      env:
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MODULE: ${{ steps.sign.outputs.signedReleaseFile }}
        COMMIT_MESSAGE: |+
          ${{ github.event.head_commit.message }}
      run: |
        ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
        curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://module%22,%22caption%22:${ESCAPED}%7D%5D"  -F module="@$MODULE"
